# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zhiyi's Blog
email: zhiyisun@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        I am Zhiyi Sun. I like Open Source Software(OSS), especially Linux. I am also a big fan of electronics gadgets. I listen 评弹 sometimes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhiyisun.github.io" # the base hostname & protocol for your site
twitter_username: zhiyisun 
github_username: zhiyisun 

# Build settings
markdown: kramdown

