# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Zhiyi's Blog
tagline:             'Good things take time'
description:         'I am Zhiyi Sun<a href="https://google.com/+ZhiyiSun" target="_blank">(+zhiyisun)</a>. I like <a href="http://opensource.org/docs/definition.php" target="_blank">Open Source Software(OSS)</a>, especially Linux. I am also a big fan of electronics gadgets.'
url:                 http://zhiyisun.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Zhiyi Sun
  url:               https://cn.linkedin.com/in/zhiyisun
  email:             zhiyisun@gmail.com

# Custom vars
version:             1.0.0
